In [1]:
import numpy as np

In [2]:
testarr = np.arange(9).reshape(3,3)

In [8]:
testarr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
p0 = testarr.T
print(p0)
print(p0.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
p1 = testarr.T[:,::-1]
print(p1)
print(p1[:,::-1].T)

[[6 3 0]
 [7 4 1]
 [8 5 2]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
p2 = testarr.T[::-1,:]
print(p2)
print(p2[::-1,:].T)

[[2 5 8]
 [1 4 7]
 [0 3 6]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
p3 = testarr.T[::-1,::-1]
print(p3)
print(p3[::-1,::-1].T)

[[8 5 2]
 [7 4 1]
 [6 3 0]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
p4 = testarr
print(p4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
p5 = testarr[:,::-1]
print(p5)
print(p5[:,::-1])

[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
p6 = testarr[::-1,:]
print(p6)
print(p6[::-1,:])

[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
p7 = testarr[::-1,::-1]
print(p7)
print(p7[::-1,::-1])

[[8 7 6]
 [5 4 3]
 [2 1 0]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
